### ISSUE TITLE
Issue is Android

### ISSUE THREAD

**Issue by sourav-android** [wirefreethought/geo-db-java-client#2]
whenever I am using the library :
implementation 'com.wirefreethought.geodb:geodb-java-client:1.4.4

It is giving me this error in Android Studio  
 com.android.tools.r8.internal.r8: Unsupported class file version: 60

I am not bale to understand how to proceed with it. Any help would be appreciated.

**Comment by wirefreethought** [comment]
This appears to indicate that your Android Studio project is configured to use a JDK older than version 16 (which is what the library is now compiled with). I found this post on how to reconfigure for a different JDK: https://www.digi.com/resources/documentation/digidocs/embedded/android/oreo/cc6/android_t_faq-change-project-jdk
